language: java
sudo: false

jdk:
    - openjdk8
    - openjdk11
    
matrix:
  allow_failures:
    - jdk: openjdk11
        
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 11 -L GPL

cache:
    directories:
        - '$HOME/.m2/repository'
